// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo-2ouEQZ3LqYUvbQ_D29wxrOKtMgcQBk',
    appId: '1:383283629229:web:db09bf3b102ddfc3298a24',
    messagingSenderId: '383283629229',
    projectId: 'pidgy-talk',
    authDomain: 'pidgy-talk.firebaseapp.com',
    storageBucket: 'pidgy-talk.firebasestorage.app',
    measurementId: 'G-MB90RE2J8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcF0aHyXJUC14ZlhtPg_6oCN9bP4c1z_s',
    appId: '1:383283629229:android:6810e1ae4b98209b298a24',
    messagingSenderId: '383283629229',
    projectId: 'pidgy-talk',
    storageBucket: 'pidgy-talk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfXWMlw3TUc3lMj0-KfnopAwFNWZ4SFwk',
    appId: '1:383283629229:ios:b760f7fb1bccacb3298a24',
    messagingSenderId: '383283629229',
    projectId: 'pidgy-talk',
    storageBucket: 'pidgy-talk.firebasestorage.app',
    iosBundleId: 'com.example.pidgyTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfXWMlw3TUc3lMj0-KfnopAwFNWZ4SFwk',
    appId: '1:383283629229:ios:b760f7fb1bccacb3298a24',
    messagingSenderId: '383283629229',
    projectId: 'pidgy-talk',
    storageBucket: 'pidgy-talk.firebasestorage.app',
    iosBundleId: 'com.example.pidgyTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo-2ouEQZ3LqYUvbQ_D29wxrOKtMgcQBk',
    appId: '1:383283629229:web:b477b9f00d1f47f9298a24',
    messagingSenderId: '383283629229',
    projectId: 'pidgy-talk',
    authDomain: 'pidgy-talk.firebaseapp.com',
    storageBucket: 'pidgy-talk.firebasestorage.app',
    measurementId: 'G-1SBFWQF823',
  );
}
